spring:
  application:
    name: paingan-oauth2
  datasource:
    url: jdbc:h2:file:~/orderdb
    driver-class-name: org.h2.Driver
    username: sa
    
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    hikari:
#      connection-timeout: 60000
#      maximum-pool-size: 20
#    password: deploypw
#    url: jdbc:mysql://172.18.186.21:3306/test?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
#    username: deployadmin
 
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        generate_statistics: true
    
  rabbitmq:
    host: localhost
    port: 5672
  security:
    user:
      name: paingan-client
      password: paingan-password
  zipkin:
    base-url: http://localhost:9411
    enabled: true
    locator:
      discovery:
        enabled: true

logging:
  level:
    org.hibernate.stat: debug
    org.hibernate.type: trace
    org.springframework.security: debug


eureka:
  client:
    enabled: true
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8900/eureka/
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 100
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
      
management:
  endpoints:
    web:
      exposure:
        include: '*'


